name: Linter
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        projects: [
          './jobs/synchronize',
          './front/tv7-twitch'
        ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
    - name: Linter
      run: |
        npm ci --include=dev
        npm run lint
      working-directory: ${{ matrix.projects }}
      env:
        CI: true
